# Generated by Django 3.0.4 on 2021-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210415_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='first_name',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='invites',
            name='last_name',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
