# Generated by Django 3.0.4 on 2021-04-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('street', models.CharField(max_length=101)),
                ('city', models.CharField(max_length=101)),
                ('state', models.CharField(max_length=101)),
                ('zip', models.CharField(blank=True, max_length=101, null=True)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=101)),
                ('co_name', models.CharField(blank=True, max_length=101, null=True)),
                ('same_address', models.BooleanField(default=False)),
                ('co_street', models.CharField(blank=True, max_length=101, null=True)),
                ('co_city', models.CharField(blank=True, max_length=101, null=True)),
                ('co_state', models.CharField(blank=True, max_length=101, null=True)),
                ('co_zip', models.CharField(blank=True, max_length=101, null=True)),
                ('co_phone', models.CharField(blank=True, max_length=18, null=True)),
                ('co_email', models.CharField(blank=True, max_length=101, null=True)),
                ('co_enabled', models.BooleanField(default=False)),
                ('co_complete', models.BooleanField(default=False)),
                ('co_separate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=51)),
                ('price', models.FloatField(default=0)),
                ('total_discount', models.FloatField(default=0)),
                ('coupon', models.FloatField(default=0)),
                ('add_discount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('cash_credit', models.FloatField(default=0)),
                ('check', models.FloatField(default=0)),
                ('finance_period', models.IntegerField(default=0)),
                ('makemodel', models.CharField(blank=True, max_length=1001, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediated.Customer')),
            ],
        ),
    ]
