# Generated by Django 3.0.4 on 2021-04-14 09:54

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_enabled', models.BooleanField(default=False)),
                ('co_complete', models.BooleanField(default=False)),
                ('co_separate', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=101, null=True)),
                ('hello_sign_ref', models.CharField(blank=True, max_length=101, null=True)),
                ('salesperson_email', models.CharField(default='developer@dcg.dev', max_length=51)),
                ('rating', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('email', models.CharField(blank=True, max_length=51, null=True)),
                ('dobY', models.CharField(blank=True, max_length=11, null=True)),
                ('dobM', models.CharField(blank=True, max_length=11, null=True)),
                ('dobD', models.CharField(blank=True, max_length=11, null=True)),
                ('ssn', models.CharField(blank=True, max_length=21, null=True)),
                ('driver_license', models.CharField(blank=True, max_length=51, null=True)),
                ('no_of_dependents', models.CharField(blank=True, max_length=21, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=21, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=21, null=True)),
                ('street', models.CharField(blank=True, max_length=101, null=True)),
                ('city', models.CharField(blank=True, max_length=101, null=True)),
                ('state', models.CharField(blank=True, max_length=101, null=True)),
                ('zip', models.CharField(blank=True, max_length=101, null=True)),
                ('years_there_first', models.CharField(blank=True, max_length=11, null=True)),
                ('own_or_rent', models.CharField(blank=True, max_length=6, null=True)),
                ('present_employer', models.CharField(blank=True, max_length=31, null=True)),
                ('years_there_second', models.CharField(blank=True, max_length=11, null=True)),
                ('job_title', models.CharField(blank=True, max_length=101, null=True)),
                ('employer_phone', models.CharField(blank=True, max_length=21, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=21, null=True)),
                ('additional_income', models.CharField(blank=True, max_length=21, null=True)),
                ('source', models.CharField(blank=True, max_length=21, null=True)),
                ('landlord_mortgage_holder', models.CharField(blank=True, max_length=51, null=True)),
                ('monthly_rent_mortgage_payment', models.CharField(blank=True, max_length=51, null=True)),
                ('cif_number', models.CharField(blank=True, max_length=101, null=True)),
                ('nortridge_cif_number', models.CharField(blank=True, max_length=101, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelloSignLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('response', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelloSignResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=200, null=True)),
                ('signer_email_address', models.CharField(blank=True, max_length=200, null=True)),
                ('signer_name', models.CharField(blank=True, max_length=101, null=True)),
                ('signer_role', models.CharField(blank=True, max_length=101, null=True)),
                ('order', models.CharField(blank=True, max_length=30, null=True)),
                ('status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('signed_at', models.CharField(blank=True, max_length=50, null=True)),
                ('last_viewed_at', models.CharField(blank=True, max_length=50, null=True)),
                ('last_reminded_at', models.CharField(blank=True, max_length=50, null=True)),
                ('has_pin', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NortridgeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=51)),
                ('price', models.FloatField(default=0)),
                ('total_discount', models.FloatField(default=0)),
                ('coupon', models.FloatField(default=0)),
                ('add_discount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('cash_credit', models.FloatField(default=0)),
                ('check', models.FloatField(default=0)),
                ('finance_period', models.IntegerField(default=0)),
                ('makemodel', models.CharField(blank=True, max_length=1001, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Preapproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('product_type', models.CharField(blank=True, max_length=51, null=True)),
                ('appliance', models.CharField(blank=True, max_length=51, null=True)),
                ('earliest_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preapproval_request', models.IntegerField(default=0)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Application')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('delivery_date', models.CharField(max_length=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainapp', to='sales.Customer'),
        ),
        migrations.AddField(
            model_name='application',
            name='co_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coapp', to='sales.Customer'),
        ),
    ]
