# Generated by Django 3.0.4 on 2021-04-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employement_status',
            field=models.BooleanField(default=False),
        ),
    ]
