# Generated by Django 3.0.4 on 2021-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_employement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
