# Generated by Django 3.0.4 on 2021-04-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210421_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_enabled', models.BooleanField(default=False)),
                ('co_complete', models.BooleanField(default=False)),
                ('co_separate', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=101, null=True)),
                ('salesperson_email', models.CharField(default='developer@dcg.dev', max_length=51)),
                ('rating', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maincreditapp', to='sales.Customer')),
                ('credit_co_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocreditapp', to='sales.Customer')),
            ],
        ),
    ]
